trigger: none

parameters:
  - name: Services
    type: object
    default:
      - azure-keyvault-secrets
      - azure-keyvault-certificates

extends:
    template: /eng/pipelines/templates/stages/archetype-sdk-tests.yml
    parameters:
      ServiceDirectory: keyvault
      Packages: ${{ parameters.Services }}
      SupportedClouds: 'Public,UsGov,China'
      TestTimeoutInMinutes: 240
      CloudConfig:
        Public:
        UsGov:
          MatrixFilters:
            - ArmTemplateParameters=^(?!.*enableHsm.*true)
        China:
          MatrixFilters:
            - ArmTemplateParameters=^(?!.*enableHsm.*true)
          Location: chinanorth3
      EnvVars:
        AZURE_TEST_RUN_LIVE: true
        AZURE_SKIP_LIVE_RECORDING: 'True'
        AZURE_CLIENT_ID: $(KEYVAULT_CLIENT_ID)
        AZURE_CLIENT_OID: $(KEYVAULT_CLIENT_OID)
        AZURE_TENANT_ID: $(KEYVAULT_TENANT_ID)
        AZURE_SUBSCRIPTION_ID: $(KEYVAULT_SUBSCRIPTION_ID)
